version: '3.8'
services:
  db:
    image: postgres:15.1-alpine
    restart: always
    container_name: postgres_server
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  backend:
    build: &build-dev
      context: ./app
      dockerfile: ./Dockerfile
    depends_on:
      - db
    environment:
      - POSTGRES_DB=db    
    ports:
      - '8000:8000'
volumes:
  db:
    driver: local