# Generated by Django 4.1.4 on 2023-01-17 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('on_hand', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VendingMachine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('building', models.CharField(max_length=50)),
                ('floor', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('quantity', models.IntegerField()),
                ('product_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
                ('vending_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vendingmachine')),
            ],
        ),
    ]
