# Generated by Django 4.1.4 on 2023-01-20 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="on_hand",
            field=models.IntegerField(default=0),
        ),
    ]
